### PR TITLE
[WIP] Rewrite the integration spec suite

### PR DESCRIPTION
**Pull request by jordansissel**

### CODE REVIEW

**Comment by jordansissel** [comment]
@purbon I'm not super happy with the way I've done the specs in this PR, but they do pass for me.

Missing pieces are facilities for factory-style fixtures, property/table-based tests for input cases, and timeout support for long running integrated services.

Would love to discuss ways to improve this going forward, but for now woudl be OK with knowledge that `rspec` passes for you as well.

**Comment by jordansissel** [comment]
For me, rspec:
```
.

Finished in 12.8 seconds (files took 0.13123 seconds to load)
1 example, 0 failures
```

**Comment by purbon** [comment]
@jordansissel specs pass without problems if I use MRI (in my case ```ruby-2.1.3```) but fail if I use jruby (in my case ```1.7.16.1```).

MRI output:
```
.
Finished in 12.69 seconds (files took 0.15179 seconds to load)
1 example, 0 failures
```

JRuby output:

```
➜  logstash-forwarder git:(feature/enable_specs_back) ✗ bundle exec rspec    

  An error occurred in an after hook
    Errno::ECHILD: No child processes - No child processes
    occurred at org/jruby/RubyProcess.java:536:in `waitpid'

F

Failures:

  1) lumberjack should follow a file and emit lines as events
     Failure/Error: connection.run do |event|
     IOError:
       closed stream
     # /Users/purbon/.rvm/gems/jruby-1.7.16.1@logstash-forwarder/gems/jruby-openssl-0.9.6-java/lib/jopenssl19/openssl/buffering.rb:447:in `close'
     # ./lib/lumberjack/server.rb:238:in `close'
     # ./lib/lumberjack/server.rb:234:in `run'
     # ./spec/lumberjack_spec.rb:83:in `(root)'

Finished in 12.71 seconds (files took 1.54 seconds to load)
1 example, 1 failure
```

hope this helps.

**Comment by purbon** [comment]
The error with the way test are run is this one:

```
within the run loop ->
* to_be_closed? false
* to_be_closed? false
* to_be_closed? true
-> close
-> data methods call to @fd.syswrite
-> ensure exception catch
-> call to close (boom!)
.
```

the way test are closing the stream within the run loop causes to close the stream before some data is willing to be written somehow. Not sure why ruby is not complaining about that, but jruby does.

I note this here in case it helps to fix or how to workaround that.

**Comment by jordansissel** [comment]
Specs pass on jruby once I merged in #367

**Pull request closed without merging**
